name: flask-portfolio
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - flask=3.0.1
  - flask-admin=1.6.1
  - flask-login=0.6.3
  - flask-migrate=4.0.5
  - flask-wtf=1.2.1
  - jmboggess::flask-sqlalchemy=3.1.1
  - pillow=10.2.0
  - pymongo=4.6.1
  - sqlalchemy=2.0.25
  - wtforms=3.0.0
