name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Choose architecture to build'
        options:
        - arm
        - x86
        - both

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.build_arch }}" == "x86" ]; then
              docker buildx build --platform linux/amd64 -t flask_portfolio .
            elif [ "${{ github.event.inputs.build_arch }}" == "arm" ]; then
              docker buildx build --platform linux/arm64 -t flask_portfolio .
            else
              docker buildx build --platform linux/amd64,linux/arm64 -t flask_portfolio .
            fi
          else
            docker buildx build --platform linux/amd64,linux/arm64 -t flask_portfolio .
          fi

      - name: Tag Docker Image
        run: docker tag flask_portfolio flask_portfolio:latest

      - name: Push Docker Image
        run: |
          docker push flask_portfolio:latest
