name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Choose architecture to build'
        options:
        - arm
        - x86
        - both

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and Push Docker Image
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.build_arch }}" == "x86" ]; then
              docker buildx build --platform linux/amd64 -t your-image-name .
            elif [ "${{ github.event.inputs.build_arch }}" == "arm" ]; then
              docker buildx build --platform linux/arm64 -t your-image-name .
            else
              docker buildx build --platform linux/amd64,linux/arm64 -t your-image-name .
            fi
          else
            docker buildx build --platform linux/amd64,linux/arm64 -t your-image-name .
          fi
          docker push your-image-name
